"""add gmail tokens

Revision ID: 72cba23cfd3c
Revises: 471039d3cfc8
Create Date: 2026-05-29 17:11:33.129057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cba23cfd3c'
down_revision: Union[str, Sequence[str], None] = '471039d3cfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gmail_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_refresh_token')
    op.drop_column('users', 'gmail_access_token')
    # ### end Alembic commands ###
